apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rks8spilt-python
  janus-idp.io/tekton: rks8spilt-python
  backstage.io/kubernetes-id: rks8spilt-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rks8spilt-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
