apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rks8spilt-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rks8spilt-python 
  name: rks8spilt-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rks8spilt-python 
